#
# Makefile for use with DJGPP on MS-DOS or Windows
#
E=.exe
O=obj
RM=deltree /y
CP=rem cp

.SUFFIXES: .obj

.c.obj:
	$(CC) $(CFLAGS) -c -o $@ $<

all:: cwsdpmi.exe

cwsdpmi.exe:
	$(CP) $(HOME)/djgpp/csdpmi5b/bin/cwsdpmi.exe cwsdpmi.exe

include common.mk
